// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Shim-SSC",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Shim-SSC",
            targets: ["AppModule"],
            bundleIdentifier: "minjae.Shim-SSC",
            teamIdentifier: "JF6B89ULG6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .butterfly),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "This app requires access to the microphone to record your voice for speech recognition."),
                .speechRecognition(purposeString: "This app requires access to speech recognition to convert your voice into text.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)